# Generated by Django 2.2.1 on 2019-05-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BolumBaskani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Adı')),
                ('bolum', models.CharField(max_length=50, verbose_name='Bolum')),
            ],
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersKodu', models.CharField(max_length=30, verbose_name='Ders Kodu')),
                ('dersAdı', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('dersiVeren', models.CharField(max_length=50, verbose_name='Dersi Veren')),
                ('dersKredisi', models.CharField(max_length=15, verbose_name='Ders Kredisi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(max_length=30, verbose_name='Bolumu')),
                ('fakulte', models.CharField(max_length=30, verbose_name='Fakultesi')),
                ('dersYuku', models.PositiveSmallIntegerField(default=10, verbose_name='dersYuku')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
