# Generated by Django 2.2.1 on 2019-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0003_auto_20190508_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bolum',
            field=models.CharField(choices=[('rap shit', 'Bilgisayar Mühendisliği'), ('Makine Mühendisliği', 'Makine Mühendisliği'), ('İnşaat Mühendisliği', 'İnşaat Mühendisliği'), ('Elektrik-Elektronik Mühendisliği', 'Elektrik-Elektronik Mühendisliği'), ('Genetik ve Biyomühendislik', 'Genetik ve Biyomühendislik'), ('Metalurji ve Malzeme Mühendisliği', 'Metalurji ve Malzeme Mühendisliği'), ('Gıda Mühendisliği', 'Gıda Mühendisliği'), ('İşletme Mühendisliği', 'İşletme Mühendisliği'), ('Endüstri Mühendisliği', 'Endüstri Mühendisliği')], max_length=50),
        ),
    ]
