# Generated by Django 2.2.1 on 2019-05-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0005_auto_20190508_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Adı')),
                ('bolum_baskani', models.CharField(max_length=50, verbose_name='Bolum Baskani')),
            ],
        ),
        migrations.DeleteModel(
            name='BolumBaskani',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistem.Bolum', verbose_name='Bolumu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dersYuku',
            field=models.PositiveSmallIntegerField(verbose_name='Ders Yuku'),
        ),
    ]
