# Generated by Django 2.2.1 on 2019-05-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0008_auto_20190508_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistem.Bolum', verbose_name='Bolumu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dersYuku',
            field=models.PositiveSmallIntegerField(verbose_name='Ders Yuku'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fakulte',
            field=models.CharField(max_length=30, verbose_name='Fakultesi'),
        ),
    ]
