# Generated by Django 2.2.1 on 2019-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0009_auto_20190508_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolumBaskani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Adı')),
                ('bolum', models.CharField(max_length=50, verbose_name='Bolum')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bolum',
            field=models.CharField(choices=[('Bilgisayar Mühendisliği', 'Bilgisayar Mühendisliği'), ('Makine Mühendisliği', 'Makine Mühendisliği'), ('İnşaat Mühendisliği', 'İnşaat Mühendisliği'), ('Elektrik-Elektronik Mühendisliği', 'Elektrik-Elektronik Mühendisliği'), ('Genetik ve Biyomühendislik', 'Genetik ve Biyomühendislik'), ('Metalurji ve Malzeme Mühendisliği', 'Metalurji ve Malzeme Mühendisliği'), ('Gıda Mühendisliği', 'Gıda Mühendisliği'), ('İşletme Mühendisliği', 'İşletme Mühendisliği'), ('Endüstri Mühendisliği', 'Endüstri Mühendisliği')], max_length=30, verbose_name='Bolumu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dersYuku',
            field=models.PositiveSmallIntegerField(verbose_name='dersYuku'),
        ),
        migrations.DeleteModel(
            name='Bolum',
        ),
    ]
