# Generated by Django 2.2.1 on 2019-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0010_auto_20190508_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dersYuku',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='dersYuku'),
        ),
    ]
