# Generated by Django 2.2.1 on 2019-05-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0011_auto_20190508_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dersYuku',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='dersYuku'),
        ),
    ]
