# Generated by Django 2.2.1 on 2019-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0012_auto_20190508_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='ikinciOgretim',
            field=models.BooleanField(default=False, verbose_name='İkinci Öğretim'),
        ),
    ]
